version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app 
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: app
    ports:
      - "127.0.0.1:3326:3306"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: always
    ports:
      - "127.0.0.1:8090:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker-compose