apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payment
  name: payment
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: payment
  type: LoadBalancer
  externalTrafficPolicy: Cluster