spring:
  datasource:
    url: 'jdbc:mysql://localhost/spring_rest_payment_for_k8s'
    username: root
    password: root@123
    tomcat:
      max-wait: '10000'
      max-active: '50'
      test-on-borrow: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: '6379'
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
  file:
    name: ./log/application.log
springdoc:
  api-docs:
    path: /api-docs
management:
  health:
    defaults:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: spring-payment-example
  prometheus:
    metrics:
      export:
        enabled: true
  appoptics:
    metrics:
      export:
        api-token: 
---
spring.config.activate.on-profile: local
---
spring.config.activate.on-profile: docker-compose
spring:
  datasource:
    url: 'jdbc:mysql://mysql/app'
    username: app
    password: app
---
spring.config.activate.on-profile: k8s
spring:
  datasource:
    url: 'jdbc:mysql://mysql/payment_k8s'
    username: root
    password: engineerpro_k8s