{
 "title": "Spring App Dashboard (Aug 25)",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Custom Metric Forbidden",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(forbidden_counter_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Status Code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Status Code per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (status) (increase(http_server_requests_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Latency ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "P99 Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(method_timed_seconds_bucket{}[1m])) by (le, method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P95 Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(method_timed_seconds_bucket{}[1m])) by (le, method))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Number Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of request per minute",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum by (uri) (increase(http_server_requests_seconds_count[1m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}